<?php
namespace Pennline\Php;

use Pennline\Php\Exception;

class Session {

	/**
	 * @var int
	 * number of seconds before garbage collection <b>may</b> intiate. when set 0,
	 * the default, the setting is ignored.
	 *
	 * session.gc_maxlifetime specifies the number of seconds after which data
	 * will be seen as 'garbage' and <b>potentially</b> cleaned up. Garbage collection
	 * may occur during session start (depending on session.gc_probability and
	 * session.gc_divisor).
	 *
	 * Note: If different scripts have different values of session.gc_maxlifetime but
	 * share the same place for storing the session data then the script with
	 * the minimum value will be cleaning the data. In this case, use this
	 * directive together with session.save_path.
	 *
	 * @link http://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime
	 */
	protected $gc_maxlifetime;

	/**
	 * @var int
	 * timestamp
	 */
	public $last_activity;

	/**
	 * @var int
	 * number of seconds allowed before session times out. when set 0,
	 * the default, the setting is ignored.
	 *
	 * This provides a back-up method in case Garbage collection does not occur.
	 * Session name is regenerated by removing the session_name() cookie instead
	 * of using session_regenerate_id() which preserves session information.
	 *
	 * @link http://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes
	 * @link http://www.owasp.org/index.php/Session_fixation
	 */
	protected $session_timeout;

	/**
	 * @param array $properties
	 */
	public function __construct( $properties = array() ) {
		$this->init();
		$this->populate( $properties );
	}

	public function cookiePresent() {
		return !empty( $_COOKIE['PHPSESSID'] );
	}

	/**
	 * @param string $key
	 * @return string
	 */
	public function getValue( $key ) {
		$result = '';
		$key = filter_var( $key, FILTER_SANITIZE_STRING );

		if ( !empty( $_SESSION[ $key ] ) ) {
			$result = filter_var( $_SESSION[ $key ], FILTER_SANITIZE_STRING );
		}

		return $result;
	}

  public function init() {
		$this->last_activity = 0;
		$this->gc_maxlifetime = 0; // 60 seconds * n minutes, e.g. 60 * 30 = 30 minutes
		$this->session_timeout = 0; // 60 seconds * n minutes, e.g. 60 * 30 = 30 minutes
  }

	/**
	 * @param array $properties
	 * @param int   $properties['gc-maxlifetime']
	 * @param int   $properties['session-timeout']
	 *
	 * @throws Exception
	 */
	protected function populate( $properties = array() ) {
		if ( !is_array( $properties ) ) {
			error_log( __METHOD__ . '() $properties provided are not an array' );
			throw new Exception( 'parameter type error', 1 );
		}

		if ( isset( $properties['gc-maxlifetime'] ) && is_int( $properties['gc-maxlifetime'] ) ) {
			$this->gc_maxlifetime = (int) $properties['gc-maxlifetime'];
		}

		if ( isset( $properties['session-timeout'] ) && is_int( $properties['session-timeout'] ) ) {
			$this->session_timeout = (int) $properties['session-timeout'];
		}
	}

  public function sessionStart() {
		if ( $this->gc_maxlifetime > 0 ) {
			ini_set ( 'session.gc-maxlifetime', $this->gc_maxlifetime );
		}

		session_start();

		if ( $this->session_timeout > 0 ) {
			$this->setLastActivity();
			$this->sessionTimeoutCheck();
		}
	}

  protected function sessionTimeoutCheck() {
		if ( $this->session_timeout <= 0 ) {
			return;
		}

    if (
			!empty( $this->last_activity ) &&
			time() - $this->last_activity > $this->session_timeout
		) {
      $this->timeoutSession();
		}
  }

	/**
	 * @param string $key
	 * @param string $value
	 */
	public function setValue( $key, $value ) {
		$_SESSION[ filter_var( $key, FILTER_SANITIZE_STRING ) ] =
			filter_var( $value, FILTER_SANITIZE_STRING );
	}

	/**
	 * $this->last_activity is used to determine whether or not to timeout the
	 * session. this method sets the class variable $this->last_activity to the
	 * session value if it exists and then updates the session value with
	 * this moment in time.
	 */
	protected function setLastActivity() {
		if ( !empty( $_SESSION['last_activity'] ) ) {
			$this->last_activity = filter_var( $_SESSION['last_activity'], FILTER_SANITIZE_STRING );
		}

		$_SESSION['last_activity'] = time();
	}

	public function timeoutSession() {
		if ( isset( $_COOKIE[ session_name() ] ) ) {
			setcookie(
					session_name(),
					'',
					time() - 42000,
					'/'
			);
		}

		session_unset();
		session_destroy();
	}

}
